track_unknown_space: true
global_frame: map
rolling_window: false

plugins:
- {name: static,              type: "costmap_2d::StaticLayer"}
- {name: polygon_layer,       type: "polygon_layer::PolygonLayer"}
#Can disable sensor layer if gmapping is fast enough to update scans
- {name: obstacles_laser,     type: "costmap_2d::ObstacleLayer"}
- {name: inflation,           type: "costmap_2d::InflationLayer"}

polygon_layer:
 resize_to_polygon: false
 frontier_travel_point: middle
 #set to false for gmapping, true if re-exploring a known area
 explore_clear_space: false
