axis_linear: 1
scale_linear: 1.5  #0.7
scale_linear_turbo: 1.5

axis_angular: 0
scale_angular: 1.5 #0.4

enable_button: 4  # Left side - upper trigger button
enable_turbo_button: 5   # Right side - upper trigger button
